version: 2.1
commands:
  run-tox:
    parameters:
      env:
        description: Tox environment
        type: string
    steps:
      # Install test dependencies and parametrize tox execution
      - checkout
      - run: sudo pip install tox codecov
      - run: tox -e << parameters.env >> && codecov

jobs:
  test-py36:
    docker:
      - image: circleci/python:3.6
    steps:
      - run-tox:
          env: "py36"
  test-py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - run-tox:
          env: "py37"
  test-py38:
    docker:
      - image: circleci/python:3.8
    steps:
      - run-tox:
          env: "py38"
  test-py39:
    docker:
      - image: circleci/python:3.9
    steps:
      - run-tox:
          env: "py39"

  lint:
    docker:
      - image: circleci/python:latest
    steps:
      - run-tox:
          env: "lint"
workflows:
  version: 2
  build:
    jobs:
      - test-py36
      - test-py37
      - test-py38
      - test-py39
      - lint
